# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mtaieb <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/09/12 11:18:12 by mtaieb            #+#    #+#              #
#    Updated: 2016/09/16 16:55:08 by mtaieb           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

SRC = main.c ft_check_argc.c ft_atoi.c ft_sum.c ft_sub.c ft_mult.c ft_div.c ft_mod.c ft_putstr.c ft_operator_to_key.c ft_putnbr.c ft_render_res.c

FLAGS = -Wall -Werror -Wextra

all:
	gcc -o $(NAME) $(SRC) $(FLAGS)

clean:
	rm -rf do-op
